// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW3uWEdcf7V1OQquy6tEPOBpKuCX06CqA',
    appId: '1:475096897278:web:28f96d57fcc2d1ddad37af',
    messagingSenderId: '475096897278',
    projectId: 'chitchat-bc530',
    authDomain: 'chitchat-bc530.firebaseapp.com',
    storageBucket: 'chitchat-bc530.appspot.com',
    measurementId: 'G-1EFBH8WY8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDefciY0Pwxoq93pV3CsLsuk1JIVjlwf9I',
    appId: '1:475096897278:android:e2341f8a3b1e6c5fad37af',
    messagingSenderId: '475096897278',
    projectId: 'chitchat-bc530',
    storageBucket: 'chitchat-bc530.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3JgDkWtGHR8SXijGbHuBIUkJMlcm7q7E',
    appId: '1:475096897278:ios:28f06dae3351d798ad37af',
    messagingSenderId: '475096897278',
    projectId: 'chitchat-bc530',
    storageBucket: 'chitchat-bc530.appspot.com',
    iosBundleId: 'com.example.chitchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3JgDkWtGHR8SXijGbHuBIUkJMlcm7q7E',
    appId: '1:475096897278:ios:28f06dae3351d798ad37af',
    messagingSenderId: '475096897278',
    projectId: 'chitchat-bc530',
    storageBucket: 'chitchat-bc530.appspot.com',
    iosBundleId: 'com.example.chitchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW3uWEdcf7V1OQquy6tEPOBpKuCX06CqA',
    appId: '1:475096897278:web:944dd5d2221171eaad37af',
    messagingSenderId: '475096897278',
    projectId: 'chitchat-bc530',
    authDomain: 'chitchat-bc530.firebaseapp.com',
    storageBucket: 'chitchat-bc530.appspot.com',
    measurementId: 'G-2BEX1C5417',
  );
}
